version: "3"

services:
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: "backend"
    ports:
      - "8080:8080"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
